"use client";

import { useState } from "react";
import { heroContent } from "@/content/hero";
import { portfolioContent } from "@/content/portfolio";
import { projects } from "@/content/projects";
import type { Locale } from "@/types/locale";
import styles from "./PortfolioChat.module.css";

type FileId="welcome"|"about"|"experience"|"stack"|"bandit"|"contact";
type Panel="explorer"|"source"|"github";
interface PortfolioChatProps{locale:Locale}
const vscodeLogo="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vscode/vscode-original.svg";
const githubAvatar="https://avatars.githubusercontent.com/u/232840488?v=4";
const githubUrl="https://github.com/emma-dasilva-dev";
const publicRepos=["bandit-redline-journal","stay","emma-dasilva-portfolio","snake","snake-arena","case-404","bsq-lite","cashless-landing-page"];
const fileIcons={tsx:"https://cdn.jsdelivr.net/gh/material-extensions/vscode-material-icon-theme@main/icons/react_ts.svg",md:"https://cdn.jsdelivr.net/gh/material-extensions/vscode-material-icon-theme@main/icons/markdown.svg",json:"https://cdn.jsdelivr.net/gh/material-extensions/vscode-material-icon-theme@main/icons/json.svg"};
const toolLogos:Record<string,string>={JavaScript:"https://cdn.simpleicons.org/javascript",TypeScript:"https://cdn.simpleicons.org/typescript",C:"https://cdn.simpleicons.org/c",HTML:"https://cdn.simpleicons.org/html5",CSS:"https://cdn.simpleicons.org/css",React:"https://cdn.simpleicons.org/react","Next.js":"https://cdn.simpleicons.org/nextdotjs/FFFFFF",Vite:"https://cdn.simpleicons.org/vite","React Router":"https://cdn.simpleicons.org/reactrouter","CSS Modules":"https://cdn.simpleicons.org/cssmodules/FFFFFF","Tailwind CSS":"https://cdn.simpleicons.org/tailwindcss","Node.js":"https://cdn.simpleicons.org/nodedotjs","Express.js":"https://cdn.simpleicons.org/express/FFFFFF","REST APIs":"https://cdn.simpleicons.org/swagger",MySQL:"https://cdn.simpleicons.org/mysql",Linux:"https://cdn.simpleicons.org/linux",Bash:"https://cdn.simpleicons.org/gnubash/FFFFFF",SSH:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/ssh/ssh-original.svg",JWT:"https://cdn.simpleicons.org/jsonwebtokens/FFFFFF",bcrypt:"https://cdn.simpleicons.org/letsencrypt",Git:"https://cdn.simpleicons.org/git",GitHub:"https://cdn.simpleicons.org/github/FFFFFF","VS Code":vscodeLogo,Postman:"https://cdn.simpleicons.org/postman",npm:"https://cdn.simpleicons.org/npm",Vercel:"https://cdn.simpleicons.org/vercel/FFFFFF",Railway:"https://cdn.simpleicons.org/railway/FFFFFF",GCC:"https://cdn.simpleicons.org/gnu/FFFFFF",Nano:"https://cdn.simpleicons.org/gnubash/FFFFFF"};
const files:{id:FileId;name:string;type:"tsx"|"md"|"json"}[]=[{id:"welcome",name:"welcome.tsx",type:"tsx"},{id:"about",name:"about.tsx",type:"tsx"},{id:"experience",name:"experience.tsx",type:"tsx"},{id:"stack",name:"stack.tsx",type:"tsx"},{id:"bandit",name:"bandit-redline.md",type:"md"},{id:"contact",name:"contact.json",type:"json"}];

export function PortfolioChat({locale}:PortfolioChatProps){
 const hero=heroContent[locale],content=portfolioContent[locale],bandit=projects.find(p=>p.slug==="bandit-redline")!;
 const [active,setActive]=useState<FileId>("welcome"),[open,setOpen]=useState<FileId[]>(["welcome"]),[panel,setPanel]=useState<Panel>("explorer"),[panelOpen,setPanelOpen]=useState(true);
 const t=locale==="en"?{explorer:"EXPLORER",source:"SOURCE CONTROL",folder:"EMMA-DASILVA-PORTFOLIO",src:"src",projects:"projects",contact:"contact",welcome:"Welcome",intro:"Cybersecurity & Computer Engineering student",copy:"I’m developing across systems, security and software engineering, with cybersecurity as my main direction.",about:"About",experience:"Experience",stack:"Stack",contactTitle:"Contact",available:"Available for internships & collaborative projects.",status:"Cybersecurity × Computer Engineering",recent:"RECENT WORK",direction:"CURRENT DIRECTION",profile:"PUBLIC PROFILE",repositories:"PUBLIC REPOSITORIES",viewProfile:"Open GitHub profile",language:"Language"}:{explorer:"EXPLORATEUR",source:"CONTRÔLE DE CODE SOURCE",folder:"EMMA-DASILVA-PORTFOLIO",src:"src",projects:"projets",contact:"contact",welcome:"Bienvenue",intro:"Étudiante en cybersécurité & génie informatique",copy:"Je me développe à travers les systèmes, la sécurité et le génie logiciel, avec la cybersécurité comme direction principale.",about:"À propos",experience:"Expérience",stack:"Stack",contactTitle:"Contact",available:"Disponible pour stages et projets collaboratifs.",status:"Cybersécurité × Génie informatique",recent:"TRAVAUX RÉCENTS",direction:"DIRECTION ACTUELLE",profile:"PROFIL PUBLIC",repositories:"DÉPÔTS PUBLICS",viewProfile:"Ouvrir le profil GitHub",language:"Langue"};
 function openFile(id:FileId){setActive(id);setOpen(v=>v.includes(id)?v:[...v,id]);}
 function closeFile(id:FileId,e:React.MouseEvent){e.stopPropagation();const next=open.filter(x=>x!==id);setOpen(next);if(active===id)setActive(next[next.length-1]??"welcome")}
 function selectPanel(next:Panel){if(panel===next){setPanelOpen(v=>!v);return}setPanel(next);setPanelOpen(true)}
 const activeFile=files.find(f=>f.id===active)!;
 return <main className={styles.ide} id="main-content">
  <header className={styles.titlebar}>
   <div className={styles.menuBar}><img src={vscodeLogo} alt="Visual Studio Code"/><span>File</span><span>Edit</span><span>Selection</span><span>View</span><span>Go</span><span>Run</span><span>Terminal</span><span>Help</span></div>
   <div className={styles.commandCenter}><CommandIcon/><span>emma-dasilva-portfolio</span></div>
   <div className={styles.windowControls} aria-hidden="true"><span>─</span><span>□</span><span>×</span></div>
  </header>
  <div className={`${styles.workbench} ${!panelOpen?styles.panelClosed:""}`}>
   <aside className={styles.activityBar} aria-label="VS Code activity bar"><ActivityButton kind="files" label={t.explorer} active={panelOpen&&panel==="explorer"} onClick={()=>selectPanel("explorer")}/><ActivityButton kind="git" label={t.source} active={panelOpen&&panel==="source"} onClick={()=>selectPanel("source")}/><ActivityButton kind="github" label="GitHub" active={panelOpen&&panel==="github"} onClick={()=>selectPanel("github")}/></aside>
   {panelOpen&&<aside className={styles.explorer}><SidePanel panel={panel} t={t} locale={locale} active={active} openFile={openFile}/></aside>}
   <section className={styles.editorArea}>
    <div className={styles.tabs}>{open.map(id=>{const f=files.find(x=>x.id===id)!;return <button key={id} className={`${styles.tab} ${active===id?styles.tabActive:""}`} onClick={()=>setActive(id)}><FileGlyph type={f.type}/><span>{f.name}</span><b onClick={e=>closeFile(id,e)}>×</b></button>})}<div className={styles.tabSpacer}/><div className={styles.editorActions} aria-hidden="true"><span>▯</span><span>•••</span></div></div>
    <div className={styles.breadcrumb}><span>emma-dasilva-portfolio</span><b>›</b><span>{activeFile.type==="md"?t.projects:activeFile.type==="json"?t.contact:t.src}</span><b>›</b><FileGlyph type={activeFile.type}/><span>{activeFile.name}</span></div>
    <div className={styles.editorFrame}><div className={styles.editor}><EditorContent id={active} locale={locale} hero={hero} content={content} bandit={bandit} t={t}/></div><div className={styles.minimap} aria-hidden="true">{Array.from({length:22},(_,i)=><i key={i} style={{width:`${30+(i*17)%58}%`}}/>)}</div></div>
   </section>
  </div>
  <footer className={styles.statusbar}><div><span><BranchIcon/> redesign-2026</span><span>↻ 0</span><span>△ 0</span></div><div><span>{t.status}</span><span>UTF-8</span><a href={`/${locale==="en"?"fr":"en"}`} title={t.language}>{locale==="en"?"Français":"English"}</a><span>⌁</span></div></footer>
 </main>
}

function SidePanel({panel,t,locale,active,openFile}:any){
 if(panel==="explorer")return <><PanelHead title={t.explorer}/><div className={styles.treeRoot}><span>⌄</span> {t.folder}</div><TreeFolder label={t.src}>{files.filter(f=>["welcome","about","experience","stack"].includes(f.id)).map(f=><FileButton key={f.id} file={f} active={active===f.id} onClick={()=>openFile(f.id)}/>)}</TreeFolder><TreeFolder label={t.projects}><FileButton file={files[4]} active={active==="bandit"} onClick={()=>openFile("bandit")}/></TreeFolder><TreeFolder label={t.contact}><FileButton file={files[5]} active={active==="contact"} onClick={()=>openFile("contact")}/></TreeFolder><div className={styles.outlineRow}>› OUTLINE</div><div className={styles.outlineRow}>› TIMELINE</div></>;
 if(panel==="source")return <><PanelHead title={t.source}/><div className={styles.sideContent}><div className={styles.branch}><BranchIcon/><strong>redesign-2026</strong></div><SideLabel>{t.recent}</SideLabel><button className={styles.workItem} onClick={()=>openFile("welcome")}><i/>Portfolio redesign</button><button className={styles.workItem} onClick={()=>openFile("bandit")}><i/>Bandit Redline</button><button className={styles.workItem} onClick={()=>openFile("stack")}><i/>{locale==="en"?"Cybersecurity preparation":"Préparation cybersécurité"}</button><SideLabel>{t.direction}</SideLabel><p className={styles.sideNote}>{locale==="en"?"Cybersecurity · Computer Engineering · Linux · Networking":"Cybersécurité · Génie informatique · Linux · Réseaux"}</p></div></>;
 return <><PanelHead title="GITHUB"/><div className={styles.sideContent}><div className={styles.githubProfile}><img src={githubAvatar} alt="Emma Da Silva GitHub avatar"/><div><strong>Emma DA SILVA</strong><span>@emma-dasilva-dev</span></div></div><SideLabel>{t.profile}</SideLabel><p className={styles.sideNote}>{publicRepos.length} {locale==="en"?"public repositories visible in this portfolio snapshot":"dépôts publics visibles dans cet aperçu"}</p><SideLabel>{t.repositories}</SideLabel><div className={styles.repoList}>{publicRepos.slice(0,5).map(repo=><a key={repo} href={`${githubUrl}/${repo}`} target="_blank" rel="noreferrer"><span>◉</span>{repo}</a>)}</div><a className={styles.panelLink} href={githubUrl} target="_blank" rel="noreferrer">{t.viewProfile} ↗</a></div></>;
}
function PanelHead({title}:{title:string}){return <div className={styles.explorerHead}>{title}<span>•••</span></div>}
function SideLabel({children}:{children:React.ReactNode}){return <h3 className={styles.sideLabel}>{children}</h3>}
function ActivityButton({kind,label,active,onClick}:{kind:string;label:string;active:boolean;onClick:()=>void}){return <button className={active?styles.activityActive:""} onClick={onClick} title={label} aria-label={label}><ActivityIcon kind={kind}/></button>}
function EditorContent({id,locale,hero,content,bandit,t}:any){
 if(id==="welcome")return <div className={styles.welcome}><div><p className={styles.comment}>// {t.welcome}</p><h1>{hero.greetingPrefix} <span>{hero.name}</span></h1><h2>{t.intro}</h2><p>{t.copy}</p><div className={styles.meta}><span>{hero.location}</span><span>{hero.status}</span></div></div><div className={styles.vscodeMark}><img src={vscodeLogo} alt="Visual Studio Code"/></div></div>;
 if(id==="about")return <Article title={t.about}><div className={styles.prose}>{content.about.paragraphs.map((p:string)=><p key={p}>{p}</p>)}<blockquote>{content.about.quote}</blockquote></div></Article>;
 if(id==="experience")return <Article title={t.experience}><div className={styles.timeline}>{content.experience.items.map((item:any)=><div key={item.period+item.title}><time>{item.period}</time><section><h2>{item.title}</h2><strong>{item.role}</strong><p>{item.description}</p>{item.link&&<a href={item.link.href} target="_blank" rel="noreferrer">{item.link.label} ↗</a>}</section></div>)}</div></Article>;
 if(id==="stack")return <Article title={t.stack}><div className={styles.stack}>{content.stack.groups.map((g:any)=><section key={g.label}><h2>{g.label}</h2><div>{g.items.map((item:string)=><span key={item}><i style={{backgroundImage:`url(${toolLogos[item]})`}}/><b>{item}</b></span>)}</div></section>)}</div></Article>;
 if(id==="bandit"){const project=locale==="en"?{copy:"Bandit Redline is a practical cybersecurity journal documenting my progress through the OverTheWire Bandit wargame. I created it to record how I approach Linux and security challenges, including the commands I use, the reasoning behind them and what I learn from each level. Through the project, I practice Linux navigation, file permissions, SSH, text processing, command-line tools and problem-solving in unfamiliar environments. For each challenge, I inspect the environment, identify the problem, test possible approaches and research unfamiliar concepts when necessary before documenting the solution and what I learned.",status:"In progress",open:"Open project notes",play:"Play OverTheWire Bandit"}:{copy:"Bandit Redline est un journal pratique de cybersécurité qui documente ma progression à travers le wargame OverTheWire Bandit. Je l’ai créé pour consigner ma manière d’aborder les défis Linux et de sécurité, notamment les commandes que j’utilise, le raisonnement derrière celles-ci et ce que j’apprends à chaque niveau. À travers ce projet, je pratique la navigation Linux, les permissions de fichiers, SSH, le traitement de texte, les outils en ligne de commande et la résolution de problèmes dans des environnements inconnus. Pour chaque défi, j’inspecte l’environnement, j’identifie le problème, je teste différentes approches et je recherche les concepts inconnus lorsque nécessaire avant de documenter la solution et ce que j’en ai appris.",status:"En cours",open:"Ouvrir les notes",play:"Jouer à OverTheWire Bandit"};return <Article title="Bandit Redline Journal"><p className={styles.projectCopy}>{project.copy}</p><div className={styles.tech}><strong>{project.status}</strong> · Linux · Bash · SSH · Git</div><div className={styles.projectLinks}><a className={styles.primaryLink} href={bandit.links.journal} target="_blank" rel="noreferrer">{project.open} ↗</a><a className={styles.primaryLink} href="https://overthewire.org" target="_blank" rel="noreferrer">{project.play} ↗</a></div></Article>}
 return <Article title={t.contactTitle}><p className={styles.lead}>{t.available}</p><div className={styles.contactLinks}>{content.contact.links.map((l:any)=><a key={l.label} href={l.href} target={l.href.startsWith("mailto:")?undefined:"_blank"} rel={l.href.startsWith("mailto:")?undefined:"noreferrer"}><span>{l.label}</span><span>↗</span></a>)}</div></Article>
}
function Article({title,children}:{title:string;children:React.ReactNode}){return <article className={styles.article}><p className={styles.comment}>// portfolio</p><h1>{title}</h1>{children}</article>}
function TreeFolder({label,children}:{label:string;children:React.ReactNode}){return <div className={styles.treeFolder}><div><span className={styles.chevron}>⌄</span><span>{label}</span></div>{children}</div>}
function FileButton({file,active,onClick}:{file:(typeof files)[number];active:boolean;onClick:()=>void}){return <button className={`${styles.file} ${active?styles.fileActive:""}`} onClick={onClick}><FileGlyph type={file.type}/><span>{file.name}</span></button>}
function FileGlyph({type}:{type:"tsx"|"md"|"json"}){return <img className={styles.fileGlyph} src={fileIcons[type]} alt=""/>}
function BranchIcon(){return <svg className={styles.inlineIcon} viewBox="0 0 16 16" aria-hidden="true"><circle cx="4" cy="3" r="1.5"/><circle cx="4" cy="13" r="1.5"/><circle cx="12" cy="7" r="1.5"/><path d="M4 4.5v7M5.5 4c4.5 0 2.5 3 5 3"/></svg>}
function CommandIcon(){return <svg viewBox="0 0 16 16" aria-hidden="true"><circle cx="7" cy="7" r="4"/><path d="m10 10 3 3"/></svg>}
function ActivityIcon({kind}:{kind:string}){const paths:any={files:<><path d="M5 3h11l3 3v15H5z"/><path d="M9 3v6h10"/><path d="M2 7v14h12"/></>,git:<><circle cx="6" cy="5" r="2"/><circle cx="6" cy="19" r="2"/><circle cx="18" cy="12" r="2"/><path d="M6 7v10M8 6c6 0 4 6 8 6"/></>,github:<path d="M12 2a10 10 0 0 0-3.2 19.5v-2.2c-2.6.6-3.2-1.1-3.2-1.1-.4-1.1-1-1.4-1-1.4-.9-.6.1-.6.1-.6 1 .1 1.5 1 1.5 1 .9 1.5 2.3 1.1 2.8.8.1-.6.3-1.1.6-1.3-2.1-.2-4.4-1.1-4.4-4.8 0-1.1.4-1.9 1-2.6-.1-.2-.4-1.2.1-2.5 0 0 .8-.3 2.7 1a9 9 0 0 1 5 0c1.9-1.3 2.7-1 2.7-1 .5 1.3.2 2.3.1 2.5.6.7 1 1.5 1 2.6 0 3.7-2.3 4.6-4.4 4.8.3.3.6.9.6 1.7v3.1A10 10 0 0 0 12 2Z"/>};return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[kind]}</svg>}
