"use client";

import { useMemo, useState } from "react";
import { heroContent } from "@/content/hero";
import { portfolioContent } from "@/content/portfolio";
import { projects } from "@/content/projects";
import type { Locale } from "@/types/locale";
import styles from "./PortfolioChat.module.css";

type FileId="welcome"|"about"|"experience"|"stack"|"bandit"|"contact";
type Panel="explorer"|"search"|"source"|"github"|"account"|"settings";
interface PortfolioChatProps{locale:Locale}
const vscodeLogo="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vscode/vscode-original.svg";
const githubAvatar="https://avatars.githubusercontent.com/u/232840488?v=4";
const githubUrl="https://github.com/emma-dasilva-dev";
const publicRepos=["bandit-redline-journal","stay","emma-dasilva-portfolio","snake","snake-arena","case-404","bsq-lite","cashless-landing-page"];
const toolLogos:Record<string,string>={JavaScript:"https://cdn.simpleicons.org/javascript",TypeScript:"https://cdn.simpleicons.org/typescript",C:"https://cdn.simpleicons.org/c",HTML:"https://cdn.simpleicons.org/html5",CSS:"https://cdn.simpleicons.org/css",React:"https://cdn.simpleicons.org/react","Next.js":"https://cdn.simpleicons.org/nextdotjs/FFFFFF",Vite:"https://cdn.simpleicons.org/vite","React Router":"https://cdn.simpleicons.org/reactrouter","CSS Modules":"https://cdn.simpleicons.org/cssmodules/FFFFFF","Tailwind CSS":"https://cdn.simpleicons.org/tailwindcss","Node.js":"https://cdn.simpleicons.org/nodedotjs","Express.js":"https://cdn.simpleicons.org/express/FFFFFF","REST APIs":"https://cdn.simpleicons.org/swagger",MySQL:"https://cdn.simpleicons.org/mysql",Linux:"https://cdn.simpleicons.org/linux",Bash:"https://cdn.simpleicons.org/gnubash/FFFFFF",SSH:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/ssh/ssh-original.svg",JWT:"https://cdn.simpleicons.org/jsonwebtokens/FFFFFF",bcrypt:"https://cdn.simpleicons.org/letsencrypt",Git:"https://cdn.simpleicons.org/git",GitHub:"https://cdn.simpleicons.org/github/FFFFFF","VS Code":vscodeLogo,Postman:"https://cdn.simpleicons.org/postman",npm:"https://cdn.simpleicons.org/npm",Vercel:"https://cdn.simpleicons.org/vercel/FFFFFF",Railway:"https://cdn.simpleicons.org/railway/FFFFFF",GCC:"https://cdn.simpleicons.org/gnu/FFFFFF",Nano:"https://cdn.simpleicons.org/gnubash/FFFFFF"};
const files:{id:FileId;name:string;type:"tsx"|"md"|"json";keywords:string}[]=[{id:"welcome",name:"welcome.tsx",type:"tsx",keywords:"emma cybersecurity computer engineering student cotonou welcome"},{id:"about",name:"about.tsx",type:"tsx",keywords:"about journey programming systems networks security"},{id:"experience",name:"experience.tsx",type:"tsx",keywords:"experience cashless cjepe internship smart reminders"},{id:"stack",name:"stack.tsx",type:"tsx",keywords:"stack javascript typescript c html css react next linux bash ssh mysql node git vscode"},{id:"bandit",name:"bandit-redline.md",type:"md",keywords:"bandit redline overthewire linux security ssh project journal"},{id:"contact",name:"contact.json",type:"json",keywords:"contact email github linkedin instagram opportunity internship"}];

export function PortfolioChat({locale}:PortfolioChatProps){
 const hero=heroContent[locale],content=portfolioContent[locale],bandit=projects.find(p=>p.slug==="bandit-redline")!;
 const [active,setActive]=useState<FileId>("welcome"),[open,setOpen]=useState<FileId[]>(["welcome"]),[panel,setPanel]=useState<Panel>("explorer"),[panelOpen,setPanelOpen]=useState(true),[query,setQuery]=useState("");
 const t=locale==="en"?{explorer:"EXPLORER",search:"SEARCH",source:"SOURCE CONTROL",github:"GITHUB",account:"ACCOUNT",settings:"SETTINGS",folder:"EMMA-PORTFOLIO",src:"src",projects:"projects",contact:"contact",welcome:"Welcome",intro:"Cybersecurity & Computer Engineering student",copy:"I’m developing across systems, security and software engineering, with cybersecurity as my main direction.",about:"About",experience:"Experience",stack:"Stack",contactTitle:"Contact",available:"Available for internships & collaborative projects.",status:"Cybersecurity × Computer Engineering",searchPlaceholder:"Search portfolio",noResults:"No matching files",recent:"RECENT WORK",direction:"CURRENT DIRECTION",profile:"PUBLIC PROFILE",repositories:"PUBLIC REPOSITORIES",viewProfile:"Open GitHub profile",language:"Language",appearance:"Appearance",theme:"Dark / Cyan",readOnly:"Portfolio preferences are read-only"}:{explorer:"EXPLORATEUR",search:"RECHERCHE",source:"CONTRÔLE DE CODE SOURCE",github:"GITHUB",account:"COMPTE",settings:"PARAMÈTRES",folder:"EMMA-PORTFOLIO",src:"src",projects:"projets",contact:"contact",welcome:"Bienvenue",intro:"Étudiante en cybersécurité & génie informatique",copy:"Je me développe à travers les systèmes, la sécurité et le génie logiciel, avec la cybersécurité comme direction principale.",about:"À propos",experience:"Expérience",stack:"Stack",contactTitle:"Contact",available:"Disponible pour stages et projets collaboratifs.",status:"Cybersécurité × Génie informatique",searchPlaceholder:"Rechercher dans le portfolio",noResults:"Aucun fichier correspondant",recent:"TRAVAUX RÉCENTS",direction:"DIRECTION ACTUELLE",profile:"PROFIL PUBLIC",repositories:"DÉPÔTS PUBLICS",viewProfile:"Ouvrir le profil GitHub",language:"Langue",appearance:"Apparence",theme:"Sombre / Cyan",readOnly:"Les préférences du portfolio sont en lecture seule"};
 const results=useMemo(()=>{const q=query.trim().toLowerCase();return q?files.filter(f=>(f.name+" "+f.keywords).toLowerCase().includes(q)):[]},[query]);
 function openFile(id:FileId){setActive(id);setOpen(v=>v.includes(id)?v:[...v,id]);}
 function closeFile(id:FileId,e:React.MouseEvent){e.stopPropagation();const next=open.filter(x=>x!==id);setOpen(next);if(active===id)setActive(next[next.length-1]??"welcome")}
 function selectPanel(next:Panel){if(panel===next){setPanelOpen(v=>!v);return}setPanel(next);setPanelOpen(true)}
 const activeFile=files.find(f=>f.id===active)!;
 return <main className={styles.ide} id="main-content">
  <header className={styles.titlebar}><div className={styles.windowDots}><i/><i/><i/></div><div className={styles.title}><img src={vscodeLogo} alt=""/><span>emma-dasilva-portfolio — Visual Studio Code</span></div><div className={styles.titleActions}><span>—</span><span>□</span><span>×</span></div></header>
  <div className={`${styles.workbench} ${!panelOpen?styles.panelClosed:""}`}>
   <aside className={styles.activityBar} aria-label="VS Code activity bar">
    <ActivityButton kind="files" label={t.explorer} active={panelOpen&&panel==="explorer"} onClick={()=>selectPanel("explorer")}/>
    <ActivityButton kind="search" label={t.search} active={panelOpen&&panel==="search"} onClick={()=>selectPanel("search")}/>
    <ActivityButton kind="git" label={t.source} active={panelOpen&&panel==="source"} onClick={()=>selectPanel("source")}/>
    <ActivityButton kind="github" label="GitHub" active={panelOpen&&panel==="github"} onClick={()=>selectPanel("github")}/>
    <div className={styles.activityBottom}><ActivityButton kind="account" label={t.account} active={panelOpen&&panel==="account"} onClick={()=>selectPanel("account")}/><ActivityButton kind="settings" label={t.settings} active={panelOpen&&panel==="settings"} onClick={()=>selectPanel("settings")}/></div>
   </aside>
   {panelOpen&&<aside className={styles.explorer}><SidePanel panel={panel} t={t} locale={locale} active={active} openFile={openFile} query={query} setQuery={setQuery} results={results}/></aside>}
   <section className={styles.editorArea}>
    <div className={styles.tabs}>{open.map(id=>{const f=files.find(x=>x.id===id)!;return <button key={id} className={`${styles.tab} ${active===id?styles.tabActive:""}`} onClick={()=>setActive(id)}><FileGlyph type={f.type}/><span>{f.name}</span><b onClick={e=>closeFile(id,e)}>×</b></button>})}</div>
    <div className={styles.breadcrumb}>emma-dasilva-portfolio <span>›</span> {activeFile.type==="md"?t.projects:activeFile.type==="json"?t.contact:t.src} <span>›</span> {activeFile.name}</div>
    <div className={styles.editor}><EditorContent id={active} locale={locale} hero={hero} content={content} bandit={bandit} t={t}/></div>
   </section>
  </div>
  <footer className={styles.statusbar}><div><span>⑂ redesign-2026</span><span>↻ 0</span><span>⚠ 0</span></div><div><span>{t.status}</span><span>UTF-8</span><a href={`/${locale==="en"?"fr":"en"}`} title={locale==="en"?"Français":"English"}>{locale==="en"?"🇬🇧 EN":"🇫🇷 FR"}</a></div></footer>
 </main>
}

function SidePanel({panel,t,locale,active,openFile,query,setQuery,results}:any){
 if(panel==="explorer")return <><PanelHead title={t.explorer}/><div className={styles.treeRoot}>⌄ {t.folder}</div><TreeFolder label={t.src}>{files.filter(f=>["welcome","about","experience","stack"].includes(f.id)).map(f=><FileButton key={f.id} file={f} active={active===f.id} onClick={()=>openFile(f.id)}/>)}</TreeFolder><TreeFolder label={t.projects}><FileButton file={files[4]} active={active==="bandit"} onClick={()=>openFile("bandit")}/></TreeFolder><TreeFolder label={t.contact}><FileButton file={files[5]} active={active==="contact"} onClick={()=>openFile("contact")}/></TreeFolder></>;
 if(panel==="search")return <><PanelHead title={t.search}/><div className={styles.searchPanel}><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.searchPlaceholder}/>{query&&<div className={styles.searchCount}>{results.length} {results.length===1?"result":"results"}</div>}{results.map((f:any)=><button key={f.id} onClick={()=>openFile(f.id)}><FileGlyph type={f.type}/><span>{f.name}</span></button>)}{query&&results.length===0&&<p>{t.noResults}</p>}</div></>;
 if(panel==="source")return <><PanelHead title={t.source}/><div className={styles.sideContent}><div className={styles.branch}>⑂ <strong>redesign-2026</strong></div><SideLabel>{t.recent}</SideLabel><button className={styles.workItem} onClick={()=>openFile("welcome")}><i/>Portfolio redesign</button><button className={styles.workItem} onClick={()=>openFile("bandit")}><i/>Bandit Redline</button><button className={styles.workItem} onClick={()=>openFile("stack")}><i/>{locale==="en"?"Cybersecurity preparation":"Préparation cybersécurité"}</button><SideLabel>{t.direction}</SideLabel><p className={styles.sideNote}>{locale==="en"?"Cybersecurity · Computer Engineering · Linux · Networking":"Cybersécurité · Génie informatique · Linux · Réseaux"}</p></div></>;
 if(panel==="github")return <><PanelHead title="GITHUB"/><div className={styles.sideContent}><div className={styles.githubProfile}><img src={githubAvatar} alt="Emma Da Silva GitHub avatar"/><div><strong>Emma DA SILVA</strong><span>@emma-dasilva-dev</span></div></div><SideLabel>{t.profile}</SideLabel><p className={styles.sideNote}>{publicRepos.length} {locale==="en"?"public repositories visible in this portfolio snapshot":"dépôts publics visibles dans cet aperçu"}</p><SideLabel>{t.repositories}</SideLabel><div className={styles.repoList}>{publicRepos.slice(0,5).map(repo=><a key={repo} href={`${githubUrl}/${repo}`} target="_blank" rel="noreferrer"><span>◉</span>{repo}</a>)}</div><a className={styles.panelLink} href={githubUrl} target="_blank" rel="noreferrer">{t.viewProfile} ↗</a></div></>;
 if(panel==="account")return <><PanelHead title={t.account}/><div className={styles.sideContent}><div className={styles.githubProfile}><img src={githubAvatar} alt="Emma Da Silva"/><div><strong>Emma Da Silva</strong><span>{locale==="en"?"Cybersecurity student":"Étudiante en cybersécurité"}</span></div></div><SideLabel>{locale==="en"?"PROFILE":"PROFIL"}</SideLabel><p className={styles.sideNote}>Cotonou, Benin<br/>{locale==="en"?"Cybersecurity × Computer Engineering":"Cybersécurité × Génie informatique"}</p><button className={styles.panelButton} onClick={()=>openFile("contact")}>{locale==="en"?"Open contact.json":"Ouvrir contact.json"}</button></div></>;
 return <><PanelHead title={t.settings}/><div className={styles.sideContent}><SideLabel>{t.language}</SideLabel><div className={styles.languageChoices}><a className={locale==="en"?styles.choiceActive:""} href="/en">🇬🇧 English</a><a className={locale==="fr"?styles.choiceActive:""} href="/fr">🇫🇷 Français</a></div><SideLabel>{t.appearance}</SideLabel><div className={styles.settingRow}><span>Theme</span><b>{t.theme}</b></div><p className={styles.sideNote}>{t.readOnly}</p></div></>;
}
function PanelHead({title}:{title:string}){return <div className={styles.explorerHead}>{title}<span>•••</span></div>}
function SideLabel({children}:{children:React.ReactNode}){return <h3 className={styles.sideLabel}>{children}</h3>}
function ActivityButton({kind,label,active,onClick}:{kind:string;label:string;active:boolean;onClick:()=>void}){return <button className={active?styles.activityActive:""} onClick={onClick} title={label} aria-label={label}><ActivityIcon kind={kind}/></button>}
function EditorContent({id,locale,hero,content,bandit,t}:any){if(id==="welcome")return <div className={styles.welcome}><div><p className={styles.comment}>// {t.welcome}</p><h1>{hero.greetingPrefix} <span>{hero.name}</span></h1><h2>{t.intro}</h2><p>{t.copy}</p><div className={styles.meta}><span>{hero.location}</span><span>{hero.status}</span></div></div><div className={styles.vscodeMark}><img src={vscodeLogo} alt="Visual Studio Code"/></div></div>;if(id==="about")return <Article title={t.about}><div className={styles.prose}>{content.about.paragraphs.map((p:string)=><p key={p}>{p}</p>)}<blockquote>{content.about.quote}</blockquote></div></Article>;if(id==="experience")return <Article title={t.experience}><div className={styles.timeline}>{content.experience.items.map((item:any)=><div key={item.period+item.title}><time>{item.period}</time><section><h2>{item.title}</h2><strong>{item.role}</strong><p>{item.description}</p>{item.link&&<a href={item.link.href} target="_blank" rel="noreferrer">{item.link.label} ↗</a>}</section></div>)}</div></Article>;if(id==="stack")return <Article title={t.stack}><div className={styles.stack}>{content.stack.groups.map((g:any)=><section key={g.label}><h2>{g.label}</h2><div>{g.items.map((item:string)=><span key={item}><i style={{backgroundImage:`url(${toolLogos[item]})`}}/><b>{item}</b></span>)}</div></section>)}</div></Article>;if(id==="bandit")return <Article title={bandit.title}><p className={styles.lead}>{bandit.subtitle[locale]}</p><p className={styles.projectCopy}>{bandit.summary[locale]}</p><div className={styles.tech}>{bandit.technologies.join(" · ")}</div><a className={styles.primaryLink} href={bandit.links.journal} target="_blank" rel="noreferrer">{locale==="en"?"Open project notes":"Ouvrir les notes"} ↗</a></Article>;return <Article title={t.contactTitle}><p className={styles.lead}>{t.available}</p><div className={styles.contactLinks}>{content.contact.links.map((l:any)=><a key={l.label} href={l.href} target={l.href.startsWith("mailto:")?undefined:"_blank"} rel={l.href.startsWith("mailto:")?undefined:"noreferrer"}><span>{l.label}</span><span>↗</span></a>)}</div></Article>}
function Article({title,children}:{title:string;children:React.ReactNode}){return <article className={styles.article}><p className={styles.comment}>// portfolio</p><h1>{title}</h1>{children}</article>}
function TreeFolder({label,children}:{label:string;children:React.ReactNode}){return <div className={styles.treeFolder}><div>⌄ <span>{label}</span></div>{children}</div>}
function FileButton({file,active,onClick}:{file:(typeof files)[number];active:boolean;onClick:()=>void}){return <button className={`${styles.file} ${active?styles.fileActive:""}`} onClick={onClick}><FileGlyph type={file.type}/><span>{file.name}</span></button>}
function FileGlyph({type}:{type:"tsx"|"md"|"json"}){return <i className={`${styles.fileGlyph} ${styles[type]}`}>{type==="tsx"?"⚛":type==="md"?"M↓":"{}"}</i>}
function ActivityIcon({kind}:{kind:string}){const paths:any={files:<><path d="M4 4h6l2 2h8v14H4z"/><path d="M8 2h8v4"/></>,search:<><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></>,git:<><circle cx="6" cy="5" r="2"/><circle cx="6" cy="19" r="2"/><circle cx="18" cy="12" r="2"/><path d="M6 7v10M8 6c6 0 4 6 8 6"/></>,github:<path d="M12 2a10 10 0 0 0-3.2 19.5v-2.2c-2.6.6-3.2-1.1-3.2-1.1-.4-1.1-1-1.4-1-1.4-.9-.6.1-.6.1-.6 1 .1 1.5 1 1.5 1 .9 1.5 2.3 1.1 2.8.8.1-.6.3-1.1.6-1.3-2.1-.2-4.4-1.1-4.4-4.8 0-1.1.4-1.9 1-2.6-.1-.2-.4-1.2.1-2.5 0 0 .8-.3 2.7 1a9 9 0 0 1 5 0c1.9-1.3 2.7-1 2.7-1 .5 1.3.2 2.3.1 2.5.6.7 1 1.5 1 2.6 0 3.7-2.3 4.6-4.4 4.8.3.3.6.9.6 1.7v3.1A10 10 0 0 0 12 2Z"/>,account:<><circle cx="12" cy="8" r="4"/><path d="M4 21c1-5 4-7 8-7s7 2 8 7"/></>,settings:<><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[kind]}</svg>}
