"use client";
/* eslint-disable @next/next/no-img-element */
import { useMemo,useRef,useState } from "react";
import { portfolioContent } from "@/content/portfolio";
import type { Locale } from "@/types/locale";
import styles from "./TerminalPortfolio.module.css";

type Command="about"|"experience"|"stack"|"projects"|"contact"|"github"|"help"|"clear";
type Entry={command:string;output?:React.ReactNode};
const githubUrl="https://github.com/emma-dasilva-dev",banditUrl="https://overthewire.org",journalUrl="https://github.com/emma-dasilva-dev/bandit-redline-journal";
const emmaAscii=String.raw`███████╗███╗   ███╗███╗   ███╗ █████╗     ██████╗  █████╗ ███████╗██╗██╗    ██╗   ██╗ █████╗
██╔════╝████╗ ████║████╗ ████║██╔══██╗    ██╔══██╗██╔══██╗██╔════╝██║██║    ██║   ██║██╔══██╗
█████╗  ██╔████╔██║██╔████╔██║███████║    ██║  ██║███████║███████╗██║██║    ██║   ██║███████║
██╔══╝  ██║╚██╔╝██║██║╚██╔╝██║██╔══██║    ██║  ██║██╔══██║╚════██║██║██║    ╚██╗ ██╔╝██╔══██║
███████╗██║ ╚═╝ ██║██║ ╚═╝ ██║██║  ██║    ██████╔╝██║  ██║███████║██║███████╗╚████╔╝ ██║  ██║
╚══════╝╚═╝     ╚═╝╚═╝     ╚═╝╚═╝  ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝╚══════╝ ╚═══╝  ╚═╝  ╚═╝`;
const logos:Record<string,string>={C:"https://cdn.simpleicons.org/c/A8B9CC",JavaScript:"https://cdn.simpleicons.org/javascript/F7DF1E",TypeScript:"https://cdn.simpleicons.org/typescript/3178C6",HTML:"https://cdn.simpleicons.org/html5/E34F26",CSS:"https://cdn.simpleicons.org/css/663399",Linux:"https://cdn.simpleicons.org/linux/FCC624",Bash:"https://cdn.simpleicons.org/gnubash/FFFFFF",SSH:"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/ssh/ssh-original.svg",React:"https://cdn.simpleicons.org/react/61DAFB","Next.js":"https://cdn.simpleicons.org/nextdotjs/FFFFFF",Vite:"https://cdn.simpleicons.org/vite/646CFF","React Router":"https://cdn.simpleicons.org/reactrouter/CA4245","CSS Modules":"https://cdn.simpleicons.org/cssmodules/FFFFFF","Tailwind CSS":"https://cdn.simpleicons.org/tailwindcss/06B6D4","Node.js":"https://cdn.simpleicons.org/nodedotjs/5FA04E","Express.js":"https://cdn.simpleicons.org/express/FFFFFF","REST APIs":"https://cdn.simpleicons.org/swagger/85EA2D",MySQL:"https://cdn.simpleicons.org/mysql/4479A1",JWT:"https://cdn.simpleicons.org/jsonwebtokens/FFFFFF",bcrypt:"https://cdn.simpleicons.org/letsencrypt/003A70",Git:"https://cdn.simpleicons.org/git/F05032",GitHub:"https://cdn.simpleicons.org/github/FFFFFF","VS Code":"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vscode/vscode-original.svg",Postman:"https://cdn.simpleicons.org/postman/FF6C37",npm:"https://cdn.simpleicons.org/npm/CB3837",Vercel:"https://cdn.simpleicons.org/vercel/FFFFFF",Railway:"https://cdn.simpleicons.org/railway/FFFFFF",GCC:"https://cdn.simpleicons.org/gnu/FFFFFF",Nano:"https://cdn.simpleicons.org/gnubash/FFFFFF"};

export function TerminalPortfolio({locale}:{locale:Locale}){
 const content=portfolioContent[locale],inputRef=useRef<HTMLInputElement>(null),glitchTimer=useRef<ReturnType<typeof setTimeout>|null>(null),[input,setInput]=useState(""),[history,setHistory]=useState<Entry[]>([]),[historyIndex,setHistoryIndex]=useState(-1),[asciiGlitch,setAsciiGlitch]=useState(false);
 const commands=useMemo(()=>["about","projects","experience","stack","contact","github","help","clear"],[]);
 const copy=locale==="en"?{launch:"./portfolio",mission:"Exploring systems, security, and software by building things that work.",identity:"CYBERSECURITY × SOFTWARE ENGINEERING",hint:"Type a command or select one below.",available:"available commands",unknown:"command not found",tip:"Tip: Linux commands work too. Try ls, pwd, whoami, or cat about.txt.",stackIntro:"tools and technologies currently in use:",githubIntro:"My GitHub contains my repositories, experiments and ongoing development work.",githubLink:"view GitHub profile",labels:{about:"learn more about me",projects:"view project work",experience:"experience & training",stack:"tools in active use",contact:"contact information",github:"view GitHub profile",help:"show commands",clear:"clear terminal"}}:{launch:"./portfolio",mission:"J'explore les systèmes, la sécurité et le logiciel en construisant des projets concrets.",identity:"CYBERSÉCURITÉ × GÉNIE LOGICIEL",hint:"Tapez une commande ou sélectionnez-en une ci-dessous.",available:"commandes disponibles",unknown:"commande introuvable",tip:"Astuce : les commandes Linux fonctionnent aussi. Essayez ls, pwd, whoami ou cat about.txt.",stackIntro:"outils et technologies actuellement utilisés :",githubIntro:"Mon GitHub contient mes dépôts, mes expérimentations et mes travaux de développement en cours.",githubLink:"voir mon profil GitHub",labels:{about:"en savoir plus sur moi",projects:"voir mes projets",experience:"expérience & formation",stack:"outils utilisés",contact:"coordonnées",github:"voir mon profil GitHub",help:"afficher les commandes",clear:"effacer le terminal"}};
 const projectTree=<div className={styles.projectOutput}><pre>{`projects/\n├── security/\n│   └── bandit-redline-journal/\n├── web/\n│   └── stay/\n└── c/\n    ├── bsq-lite/\n    ├── case-404/\n    └── snake/`}</pre><p>{locale==="en"?"Security learning, full-stack development, and C projects in one workspace.":"Apprentissage en sécurité, développement full-stack et projets C dans un même espace."}</p></div>;
 function triggerAsciiGlitch(){if(glitchTimer.current)clearTimeout(glitchTimer.current);setAsciiGlitch(false);requestAnimationFrame(()=>requestAnimationFrame(()=>setAsciiGlitch(true)));glitchTimer.current=setTimeout(()=>setAsciiGlitch(false),1050)}
 function outputFor(command:Command):React.ReactNode{if(command==="help")return <CommandList commands={commands} labels={copy.labels} onRun={runCommand}/>;if(command==="about")return <div className={styles.textOutput}>{content.about.paragraphs.map(p=><p key={p}>{p}</p>)}</div>;if(command==="experience")return <div className={styles.timeline}>{content.experience.items.map(item=><div key={item.period+item.title}><span>{item.period}</span><section><strong>{item.title}</strong><em>{item.role}</em><p>{item.description}</p></section></div>)} </div>;if(command==="stack"){const items=Array.from(new Set(content.stack.groups.flatMap(g=>g.items)));return <div className={styles.stackOutput}><p>{copy.stackIntro}</p><div className={styles.stackGrid}>{items.map(item=><span className={styles.logoTile} key={item} title={item}><img src={logos[item]} alt={item}/></span>)}</div></div>}if(command==="projects")return projectTree;if(command==="contact")return <div className={styles.links}>{content.contact.links.map(link=><a key={link.label} href={link.href} target={link.href.startsWith("mailto:")?undefined:"_blank"} rel="noreferrer">{link.label}<span>↗</span></a>)}</div>;if(command==="github")return <div className={styles.projectOutput}><p>{copy.githubIntro}</p><div><a href={githubUrl} target="_blank" rel="noreferrer">{copy.githubLink} ↗</a></div></div>;return null}
 function linuxOutput(raw:string):React.ReactNode|undefined{const command=raw.trim().toLowerCase().replace(/\s+/g," ");if(command==="ls"||command==="ls -la")return <pre>{`about.txt   contact.sh   experience.log   projects/   stack/`}</pre>;if(command==="pwd")return <p>/home/emma/portfolio</p>;if(command==="whoami")return <div className={styles.textOutput}><p>emma dasilva</p><p>{copy.identity.toLowerCase()}</p></div>;if(command==="cat about.txt")return outputFor("about");if(command==="cat experience.log")return outputFor("experience");if(command==="./contact.sh")return outputFor("contact");if(command==="ls projects"||command==="ls projects/"||command==="tree projects"||command==="tree projects/")return projectTree;if(command==="ls stack"||command==="ls stack/")return outputFor("stack");if(command==="cd projects"||command==="cd projects/")return <p>{locale==="en"?"projects/ selected — use 'ls projects' to inspect the workspace.":"projects/ sélectionné — utilisez 'ls projects' pour inspecter l'espace."}</p>;if(command==="cat bandit-redline-journal"||command==="cat projects/security/bandit-redline-journal")return <div className={styles.projectOutput}><strong>Bandit Redline Journal</strong><p>{locale==="en"?"A practical cybersecurity journal documenting my progress through OverTheWire Bandit, using Linux, Bash, SSH and command-line problem solving.":"Un journal pratique de cybersécurité documentant ma progression sur OverTheWire Bandit avec Linux, Bash, SSH et la résolution de problèmes en ligne de commande."}</p><div><a href={journalUrl} target="_blank" rel="noreferrer">journal ↗</a><a href={banditUrl} target="_blank" rel="noreferrer">OverTheWire ↗</a></div></div>;return undefined}
 function runCommand(raw:string){const command=raw.trim();if(!command)return;if(command.toLowerCase()==="clear"){setHistory([]);setInput("");setHistoryIndex(-1);return}const normalized=command.toLowerCase();const valid=commands.includes(normalized);const linux=linuxOutput(command);setHistory(prev=>[...prev,{command,output:valid?outputFor(normalized as Command):linux??<p className={styles.error}>{`bash: ${command}: ${copy.unknown}. type 'help'.`}</p>}]);setInput("");setHistoryIndex(-1);requestAnimationFrame(()=>document.querySelector(`.${styles.terminalBody}`)?.scrollTo({top:99999,behavior:"smooth"}))}
 function navigateHistory(direction:number){const h=history.map(x=>x.command);if(!h.length)return;const next=historyIndex<0?h.length-1:Math.max(0,Math.min(h.length-1,historyIndex+direction));setHistoryIndex(next);setInput(h[next])}
 return <main className={`${styles.desktop} ${asciiGlitch?styles.desktopGlitch:""}`} onClick={()=>inputRef.current?.focus()}><div className={styles.menuBar}><div><span className={styles.apple}>●</span><strong>Terminal</strong><span>Shell</span><span>Edit</span><span>View</span><span>Window</span><span>Help</span></div><div><span>⌁</span><span>◉</span><span>{locale==="en"?"EN":"FR"}</span></div></div><section className={styles.terminalWindow} aria-label="Interactive terminal portfolio"><header className={styles.terminalHeader}><div className={styles.lights}><i/><i/><i/></div><span>emma@portfolio: ~</span><a className={styles.languageSwitch} href={`/${locale==="en"?"fr":"en"}`} onClick={e=>e.stopPropagation()}><span className={locale==="en"?styles.languageActive:""}>EN</span><span className={locale==="fr"?styles.languageActive:""}>FR</span></a></header><div className={styles.terminalBody}><section className={styles.intro}><p className={styles.launch}><Prompt/> {copy.launch}</p><div className={`${styles.asciiIdentity} ${asciiGlitch?styles.asciiGlitch:""}`} role="button" tabIndex={0} aria-label="Animate Emma DaSilva identity" onClick={e=>{e.stopPropagation();triggerAsciiGlitch()}} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();triggerAsciiGlitch()}}}><pre data-text={emmaAscii}>{emmaAscii}</pre><p><span>&gt;</span> {copy.identity}</p></div><p className={styles.mission}>{copy.mission}</p><p className={styles.hint}>{copy.hint}</p><p className={styles.sectionLabel}>{copy.available}:</p><CommandList commands={commands} labels={copy.labels} onRun={runCommand}/><p className={styles.tip}>{copy.tip}</p></section>{history.map((entry,index)=><div className={styles.entry} key={`${entry.command}-${index}`}><p><Prompt/> {entry.command}</p>{entry.output}</div>)}<form className={styles.promptLine} onSubmit={e=>{e.preventDefault();runCommand(input)}}><Prompt/><span className={styles.inputShell}><input ref={inputRef} value={input} style={{width:`${Math.max(1,input.length)}ch`}} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="ArrowUp"){e.preventDefault();navigateHistory(-1)}if(e.key==="ArrowDown"){e.preventDefault();navigateHistory(1)}}} aria-label="Terminal command" autoCapitalize="none" autoComplete="off" spellCheck={false}/><span className={styles.blockCursor} aria-hidden="true"/></span></form></div></section><nav className={styles.dock} aria-label="Desktop dock"><span>◉</span><span>⌘</span><span className={styles.dockActive}>›_</span><span>◈</span><span>◆</span></nav></main>}
function Prompt(){return <><strong className={styles.user}>emma@portfolio</strong><span className={styles.path}>:~$</span></>}
function CommandList({commands,labels,onRun}:{commands:string[];labels:Record<string,string>;onRun:(command:string)=>void}){return <div className={styles.commandList}>{commands.map(command=><button type="button" key={command} onClick={e=>{e.stopPropagation();onRun(command)}}><strong>{command}</strong><span>{labels[command]}</span></button>)}</div>}
